# Generated by Django 5.0.7 on 2024-08-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_trainingmodule_color'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='allowed_modules',
            field=models.ManyToManyField(blank=True, related_name='allowed_institutions', to='modules.trainingmodule'),
        ),
    ]
