# Generated by Django 5.0.7 on 2024-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_alter_activity_activity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satisfactionquestion",
            name="level_of_satisfaction",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Dissatisfied"),
                    (2, "Dissatisfied"),
                    (3, "Neutral"),
                    (4, "Satisfied"),
                    (5, "Very Satisfied"),
                ],
                null=True,
            ),
        ),
    ]
