# Generated by Django 5.0.7 on 2024-08-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_remove_video_uploaded_at_remove_video_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmodule",
            name="module_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
