# Generated by Django 5.0.7 on 2024-08-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0006_alter_trainingmodule_module_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudForumParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="cloud_forum_participation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.cloudforumparticipation",
            ),
        ),
    ]
