# Generated by Django 5.0.7 on 2024-08-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0008_image_activity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectionmultiplequestionary",
            name="question_text",
            field=models.TextField(),
        ),
    ]
