# Generated by Django 5.0.7 on 2024-08-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0009_alter_selectionmultiplequestionary_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitymodule",
            name="co_create_aproximate_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useractivitymodule",
            name="engage_aproximate_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useractivitymodule",
            name="foundations_aproximate_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useractivitymodule",
            name="reflection_aproximate_duration",
            field=models.IntegerField(default=0),
        ),
    ]
